pipeline {
    agent none

    options {
        ansiColor('xterm')
        // parallelsAlwaysFailFast()
        timestamps()
    }

    stages {
        stage("Test") {
            parallel {

                stage('Fedora 31 (mock)') {
                    agent { label "fedora31" }
                    steps { sh "schutzbot/run_tests.sh" }
                }

                stage('Fedora 32 (mock)') {
                    agent { label "fedora32" }
                    steps { sh "schutzbot/run_tests.sh" }
                }

                stage('RHEL 8.2 (mock)') {
                   agent { label "rhel82" }
                   steps { sh "schutzbot/run_tests.sh" }
                }

                stage('Fedora 32 (os)') {
                    agent { label "fedora32" }
                    environment {
                        DEPLOY_REPO = "yes"
                        EXTRA_VARS = "-e install_source=os"
                    }
                    steps { sh "schutzbot/run_tests.sh" }
                }

            }
        }
    }
}
