pipeline {
    agent none

    options {
        timestamps()
        ansiColor('xterm')
    }

    stages {
        stage("Functional tests") {
            parallel {

                stage('Fedora 31') {
                    agent { label "fedora31" }
                    steps { sh "jenkins/run_tests.sh" }
                }

                stage('Fedora 32') {
                    agent { label "fedora32" }
                    steps { sh "jenkins/run_tests.sh" }
                }

                stage('RHEL 8.2') {
                    agent { label "rhel82" }
                    steps { sh "jenkins/run_tests.sh" }
                }

                stage('RHEL 8.3') {
                    agent { label "rhel83" }
                    steps { sh "jenkins/run_tests.sh" }
                }

            }
        }
    }
}